apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    field.cattle.io/creatorId: user-jqbjb
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.86.10"],"port":443,"protocol":"HTTPS","serviceName":"world0:ingress-d055992b3f18d1af6b28968b10dc2c09","ingressName":"world0:www-hev","hostname":"hev.n7sa.com","path":"/","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-world0-www-hev
  name: www-hev
  namespace: world0
  selfLink: /apis/apps/v1beta2/namespaces/world0/deployments/www-hev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-world0-www-hev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-07-07T19:40:11Z"
        workload.cattle.io/state: '{"":"c-l4n65:m-54dd8c836762","YmlnbWE=":"c-pt2rr:m-54dd8c836762"}'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-world0-www-hev
    spec:
      containers:
      - image: rancher.n7sa.com:5000/skynet/hev:v0.2.11
        imagePullPolicy: Always
        name: www-hev
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /hev/external/openvpn
          name: openpvn
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: rancher
      nodeName: bigma
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /minio/rancher-data/by-name/openvpn/pki
          type: ""
        name: openpvn
status: {}
